import 'package:stayegy/bloc/Repository/Hotels/HotelDetails.dart';
import 'package:stayegy/bloc/Repository/User/User_Details.dart';

List<String> cityImageList = [
  'images/cityImages/dhaka.jpeg',
  'images/cityImages/kustia.jpg',
  'images/cityImages/chittagong.jpg',
  'images/cityImages/cox\'sbazar.jpeg',
  'images/cityImages/sylhet.jpeg',
  'images/cityImages/rajshashi.jpg',
  'images/cityImages/mymensingh.jpg',
  'images/cityImages/gopalganj.jpg',
  'images/cityImages/barishal.jpeg',
  'images/cityImages/bandarban.jpg',
];

List<String> offerImage = [
  'images/offer 1.png'
      'images/offer 2.png'
];

List<String> offerImage1 = [
  'images/collection 1.png',
];
List<String> concerning = [
  'images/grettings.png',
  'images/T&C.png',
  'images/Contact.png',
];
List<int> noOfRoomList = [
  1,
  2,
  3,
];

UserDetails userDetailsGlobal;

List<Hotel> homePageHotels;

List<String> cityList = [
  "Dhaka",
  "Uttara",
  "Adabor",
  "Uttar Khan",
  "Kadamtali",
  "Kalabagan",
  "Kafrul",
  "Kamrangrichar",
  "Cantonment",
  "Kotwali",
  "Khilkhet",
  "Khilgaon",
  "Gulshan",
  "Gendaria",
  "Chawkbazar Model",
  "Demra",
  "Turag",
  "Tejgaon",
  "Tejgaon I/A",
  "Dakshinkhan",
  "Darus Salam",
  "Dhanmondi",
  "New Market",
  "Paltan",
  "Pallabi",
  "Bangshal",
  "Badda",
  "Bimanbandar",
  "Motijheel",
  "Mirpur Model",
  "Mohammadpur",
  "Jatrabari",
  "Ramna",
  "Rampura",
  "Lalbagh",
  "Shah Ali",
  "Shahbagh",
  "Sher-e-Bangla Nagar",
  "Shyampur",
  "Sabujbagh",
  "Sutrapur",
  "Hazaribagh",
  "Chittagong",
  "Kotwali",
  "Khulshi",
  "Chandgoan",
  "Double Mooring",
  "Patenga",
  "Panchlaish",
  "Pahartali",
  "Bandar",
  "Bakalia",
  "Bayejid Bostami",
  "Halishahar",
  "Hathazari Upazila",
  "Teknaf",
  "Teknaf",
  "Baharchhara",
  "Sabrang",
  "Whykong",
  "Nhilla",
  "St. Martins Dwip",
  "Cox's Bazar",
  "Ukhia",
  "Cox's Bazar Sadar",
  "Kutubdia",
  "Chakaria",
  "Teknaf",
  "Pekua",
  "Maheshkhali",
  "Ramu",
  "Panchagarh",
  "Atwari",
  "Tentulia",
  "Debiganj",
  "Panchagarh Sadar",
  "Boda",
  "Thakurgaon",
  "Thakurgaon Sadar",
  "Pirganj",
  "Baliadangi",
  "Ranisankail",
  "Haripur",
  "Pirganj"
      "Kusha Raniganj",
  "Khangaon",
  "Jabarhat",
  "Daulatpur",
  "Pirganj",
  "Bairchuna",
  "Bhomradaha",
  "Sengaon",
  "Saidpur",
  "Hajipur",
  "Nilphamari",
  "Kishoreganj",
  "Jaldhaka",
  "Dimla",
  "Domar",
  "Nilphamari Sadar",
  "Saidpur",
  "Saidpur",
  "Kamar Pukur",
  "Kushiram Belpukur",
  "Bangalipur",
  "Bothlagari",
  "Khata Madhupur",
  "Lalmonirhat",
  "Aditmari",
  "Kaliganj",
  "Patgram",
  "Lalmonirhat Sadar",
  "Hatibandha",
  "Dinajpur",
  "Kaharole",
  "Khansama",
  "Ghoraghat",
  "Chirirbandar",
  "Dinajpur Sadar",
  "Nawabganj",
  "Parbatipur",
  "Fulbari",
  "Biral",
  "Birampur",
  "Birganj",
  "Bochaganj",
  "Hakimpur",
  "Rangpur",
  "Kaunia",
  "Gangachara",
  "Taraganj",
  "Pirganj",
  "Pirgachha",
  "Badarganj",
  "Mitha Pukur",
  "Rangpur Sadar",
  "Kurigram",
  "Ajmiriganj",
  "Chunarughat",
  "Nabiganj",
  "Baniachong",
  "Bahubal",
  "Madhabpur",
  "Lakhai",
  "Habiganj Sadar",
  "Gaibandha",
  "Gaibandha Sadar",
  "Gobindaganj",
  "Palashbari",
  "Fulchhari",
  "Saghatta",
  "Sadullapur",
  "Sundarganj",
  "Joypurhat",
  "Akkelpur",
  "Kalai",
  "Khetlal",
  "Joypurhat Sadar",
  "Panchbibi",
  "Nawabganj",
  "Gomastapur",
  "Nawabganj Sadar",
  "Nachole",
  "Bholahat",
  "Shibganj",
  "Naogaon",
  "Atrai",
  "Dhamoirhat",
  "Niamatpur",
  "Patnitala",
  "Porsha",
  "Badalgachhi",
  "Mahadebpur",
  "Manda",
  "Naogaon Sadar",
  "Raninagar",
  "Sapahar",
  "Bogra",
  "Adamdighi",
  "Kahaloo",
  "Gabtali",
  "Dhupchanchia",
  "Dhunat",
  "Nandigram",
  "Bogra sadar",
  "Shahjahanpur",
  "Shibganj",
  "Sherpur",
  "Sariakandi",
  "Sonatala",
  "Rajshahi",
  "Godagari",
  "Charghat",
  "Tanore",
  "Durgapur",
  "Paba",
  "Puthia",
  "Baghmara",
  "Bagha",
  "Mohanpur",
  "Natore",
  "Gurudaspur",
  "Natore Sadar",
  "Baraigram",
  "Bagatipara",
  "Lalpur",
  "Singra",
  "Sirajganj",
  "Ullahpara",
  "Kazipur",
  "Kamarkhanda",
  "Chauhali",
  "Tarash",
  "Belkuchi",
  "Raiganj",
  "Shahjadpur",
  "Sirajganj Sadar",
  "Pabna",
  "Atgharia",
  "Ishwardi",
  "Chatmohar",
  "Pabna Sadar",
  "Bera",
  "Bhangura",
  "Santhia",
  "Sujanagar",
  "Kushtia",
  "Kumarkhali",
  "Kushtia Sadar",
  "Khoksa",
  "Daulatpur",
  "Bheramara",
  "Mirpur",
  "Meherpur",
  "Gangni",
  "Mujibnagar",
  "Meherpur Sadar",
  "Chuadanga",
  "Alamdanga",
  "Chuadanga Sadar",
  "Jiban Nagar",
  "Damurhuda",
  "Jhenaidah",
  "Kaliganj",
  "Kotchandpur",
  "Jhenaidah Sadar",
  "Maheshpur",
  "Shailkupa",
  "Harinakunda",
  "Magura",
  "Magura Sadar",
  "Mohammadpur",
  "Shalikha",
  "Sreepur",
  "Rajbari",
  "Goalanda",
  "Pangsha",
  "Baliakandi",
  "Rajbari Sadar",
  "Faridpur",
  "Alfadanga",
  "Char Bhadrasan",
  "Nagarkanda",
  "Faridpur Sadar",
  "Boalmari",
  "Bhanga",
  "Madhukhali",
  "Sadarpur",
  "Saltha",
  "Narail",
  "Kalia",
  "Narail Sadar",
  "Lohagara",
  "Jessore",
  "Abhaynagar",
  "Keshabpur",
  "Chaugachha",
  "Jhikargachha",
  "Bagherpara",
  "Manirampur",
  "Jessore Sadar",
  "Sharsha",
  "Khulna",
  "Koyra",
  "Dumuria",
  "Terokhada",
  "Dacope",
  "Dighalia",
  "Paikgachha",
  "Phultala",
  "Batiaghata",
  "Rupsa",
  "Satkhira",
  "Assasuni",
  "Kalaroa",
  "Kaliganj",
  "Tala",
  "Debhata",
  "Shyamnagar",
  "Satkhira Sadar",
  "Bagerhat",
  "Kachua",
  "Chitalmari",
  "Fakirhat",
  "Bagerhat Sadar",
  "Mongla",
  "Morrelganj",
  "Mollahat",
  "Rampal",
  "Sarankhola",
  "Pirojpur",
  "Kawkhali",
  "Zianagar",
  "Nazirpur",
  "Nesarabad",
  "Pirojpur Sadar",
  "Bhandaria",
  "Mathbaria",
  "Madaripur",
  "Kalkini",
  "Madaripur Sadar",
  "Rajoir",
  "Shibchar",
  "Gopalganj",
  "Kashiani",
  "Kotalipara",
  "Gopalganj Sadar",
  "Tungipara",
  "Muksudpur",
  "Barisal",
  "Agailjhara",
  "Wazirpur",
  "Gaurnadi",
  "Barisal Sadar",
  "Bakerganj",
  "Banaripara",
  "Babuganj",
  "Muladi",
  "Mehendiganj",
  "Hizla",
  "Jhalokati",
  "Kathalia",
  "Jhalokati Sadar",
  "Nalchity",
  "Rajapur",
  "Patuakhali",
  "Kalapara",
  "Galachipa",
  "Dashmina",
  "Dumki",
  "Patuakhali Sadar",
  "Bauphal",
  "Mirzaganj",
  "Barguna",
  "Amtali",
  "Patharghata",
  "Barguna Sadar",
  "Bamna",
  "Betagi",
  "Bhola",
  "Adamdighi",
  "Char Fasson",
  "Tazumuddin",
  "Daulat Khan",
  "Burhanuddin",
  "Bhola Sadar",
  "Manpura",
  "Lalmohan",
  "Sherpur",
  "Jhenaigati",
  "Nakla",
  "Nalitabari",
  "Sherpur Sadar",
  "Sreebardi",
  "Jamalpur",
  "Islampur",
  "Jamalpur Sadar",
  "Dewanganj",
  "Bakshiganj",
  "Madarganj",
  "Melandaha",
  "Sarishabari",
  "Mymensingh",
  "Ishwarganj",
  "Gaffargaon",
  "Gauripur",
  "Trishal",
  "Dhobaura",
  "Nandail",
  "Phulpur",
  "Fulbaria",
  "Bhaluka",
  "Mymensingh Sadar",
  "Muktagachha",
  "Haluaghat",
  "Tangail",
  "Kalihati",
  "Gopalpur",
  "Ghatail",
  "Tangail Sadar",
  "Delduar",
  "Dhanbari",
  "Nagarpur",
  "Basail",
  "Bhuapur",
  "Madhupur",
  "Mirzapur",
  "Sakhipur",
  "Gazipur",
  "Kapasia",
  "Kaliakair",
  "Kaliganj",
  "Gazipur Sadar",
  "Sreepur",
  "Manikganj",
  "Ghior",
  "Daulatpur",
  "Manikganj Sadar",
  "Shibalaya",
  "Saturia",
  "Singair",
  "Harirampur",
  "Kishoreganj",
  "Austagram",
  "Itna",
  "Katiadi",
  "Karimganj",
  "Kishoreganj Sadar",
  "Kuliarchar",
  "Tarail",
  "Nikli",
  "Pakundia",
  "Bajitpur",
  "Bhairab",
  "Mithamain",
  "Hossainpur",
  "Narsingdi",
  "Narsingdi Sadar",
  "Palash",
  "Belabo",
  "Monohardi",
  "Raipura",
  "Shibpur",
  "Narayanganj",
  "Gomastapur",
  "Nawabganj Sadar",
  "Nachole",
  "Bholahat",
  "Shibganj",
  "Munshiganj",
  "Gazaria",
  "Tongibari",
  "Munshiganj Sadar",
  "Lohajang",
  "Sreenagar",
  "Serajdikhan",
  "Comilla",
  "Comilla Adarsha Sadar",
  "Chandina",
  "Chauddagram",
  "Titas",
  "Daudkandi",
  "Debidwar",
  "Barura",
  "Burichang",
  "Brahmanpara",
  "Manoharganj",
  "Muradnagar",
  "Meghna",
  "Laksam",
  "Nangalkot",
  "Comilla Sadar Dakshin",
  "Homna",
  "Chandpur",
  "Kachua",
  "Chandpur Sadar",
  "Faridganj",
  "Matlab Uttar",
  "Matlab Dakshin",
  "Shahrasti",
  "Haimchar",
  "Hajiganj",
  "Lakshmipur",
  "Kamalnagar",
  "Ramganj",
  "Ramgati",
  "Raipur",
  "Lakshmipur Sadar",
  "Laksham Upazila",
  "Ajgara",
  "Uttardah",
  "Kandirpar",
  "Gobindapur",
  "Bakai",
  "Mudafarganj",
  "Laksham",
  "Noakhali",
  "Kabirhat",
  "Companiganj",
  "Chatkhil",
  "Noakhali Sadar",
  "Begumganj",
  "Senbagh",
  "Subarnachar",
  "Sonaimuri",
  "Hatiya",
  "Sunamganj",
  "Chhatak",
  "Jagannathpur",
  "Jamalganj",
  "Tahirpur",
  "Dakshin Sunamganj",
  "Derai",
  "Dowarabazar",
  "Dharampasha",
  "Bishwambarpur",
  "Sulla",
  "Sunamganj Sadar",
  "Sylhet",
  "Kanaighat",
  "Companiganj",
  "Gowainghat",
  "Golabganj",
  "Zakiganj",
  "Jaintiapur",
  "Dakshin Surma",
  "Fenchuganj",
  "Balaganj",
  "Beanibazar",
  "Bishwanath",
  "Sylhet Sadar",
  "Maulvibazar",
  "Kamalganj",
  "Kulaura",
  "Juri",
  "Maulvibazar Sadar",
  "Barlekha",
  "Rajnagar",
  "Sreemangal",
  "Habiganj",
  "Ajmiriganj",
  "Chunarughat",
  "Nabiganj",
  "Baniachong",
  "Bahubal",
  "Madhabpur",
  "Lakhai",
  "Habiganj Sadar",
  "Brahmanbaria",
  "Akhaura",
  "Ashuganj",
  "Kasba",
  "Nabinagar",
  "Nasirnagar",
  "Banchharampur",
  "Brahmanbaria Sadar",
  "Sarail",
  "Feni",
  "Chhagalnaiya",
  "Daganbhuiyan",
  "Parshuram",
  "Fulgazi",
  "Feni Sadar",
  "Sonagazi",
  "Khagrachhari",
  "Khagrachhari Sadar",
  "Dighinala",
  "Panchhari",
  "Mahalchhari",
  "Matiranga",
  "Manikchhari",
  "Ramgarh",
  "Lakshmichhari",
  "Rangamati",
  "Kawkhali",
  "Kaptai",
  "Juraichhari",
  "Naniarchar",
  "Barkal",
  "Baghaichhari",
  "Belaichhari",
  "Rangamati Sadar",
  "Rajasthali",
  "Langadu",
  "Bandarban",
  "Alikadam",
  "Thanchi",
  "Naikhongchhari",
  "Bandarban Sadar",
  "Ruma",
  "Rowangchhari",
  "Lama",
  "Satkhira",
  "Assasuni",
  "Kalaroa",
  "Kaliganj",
  "Tala",
  "Debhata",
  "Shyamnagar",
  "Satkhira Sadar",
  "Thanchi Upazila",
  "Tindu",
  "Thanchi",
  "Balipara",
  "Remakry",
];
